In [1]:
from sklearn.feature_extraction.text import CountVectorizer 

In [2]:
vect = CountVectorizer(binary = True)
#corpus with three documents 
corpus = ["Is this the real life","Is this just fantasy","caught in the limelight, no escape from reality"]

In [3]:
type(corpus)

list

In [4]:
vect.fit(corpus)

CountVectorizer(binary=True)

In [5]:
vocab = vect.vocabulary_

In [6]:
vocab

{'nlp': 4,
 'is': 3,
 'awesome': 1,
 'want': 11,
 'to': 7,
 'start': 5,
 'an': 0,
 'company': 2,
 'top': 8,
 'unicorns': 9,
 'use': 10,
 'techniques': 6}

In [7]:
vect.transform(["", "I want to start an NLP company", "Top unicorns use NLP techniques"]).toarray()

array([[0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0]], dtype=int64)

In [8]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

def cosine_similarity_text(texts):
    """
    Calculates the cosine similarity between all pairs of texts in a list.
    """
    # create TfidfVectorizer object
    vectorizer = TfidfVectorizer()

    # create sparse matrix of text vectors
    text_vectors = vectorizer.fit_transform(texts)

    # convert sparse matrix to dense matrix
    dense_vectors = text_vectors.todense()

    # calculate cosine similarity
    cos_sim = np.dot(dense_vectors, dense_vectors.T)

    return cos_sim

In [9]:
cos_sim = cosine_similarity_text(corpus)
print(cos_sim)

[[1.         0.09841374 0.10914377]
 [0.09841374 1.         0.07232613]
 [0.10914377 0.07232613 1.        ]]


In [10]:
from sklearn.metrics.pairwise import cosine_similarity 

In [11]:
similarity = cosine_similarity((vect.transform(["My name is Pragati"]).toarray()),vect.transform(["I a studying NLP"]).toarray())

In [12]:
similarity

array([[0.]])